// Writes the catalog with sources for the app, like the arena:bots plugin of build.mjs.
import { writeFile } from "node:fs/promises";
import { loadBots } from "../../../packages/bot-catalog-node.js";
const bots = (await loadBots()).map(({ file, ...bot }) => bot);
await writeFile(new URL("../src/generated/bots.ts", import.meta.url),
  `// Generated by tools/bots.mjs, do not edit.\nexport const BOTS = ${JSON.stringify(bots)} as const;\n`);
console.log(`${bots.length} controllers`);
