import { build } from "esbuild";
import { execFile } from "node:child_process";
import { mkdir, readFile, writeFile, cp, lstat, realpath, rm } from "node:fs/promises";
import { resolve, dirname, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { loadBots } from "../packages/bot-catalog-node.js";
import { renderSite } from "../packages/site/prerender.js";

const bots = await loadBots();
const root = await realpath(fileURLToPath(new URL("../", import.meta.url)));
const dist = resolve(root, "dist");
const web = resolve(root, "apps/web");
// Only the generated directory directly inside this project may be removed.
if (dirname(dist) !== root) throw new Error("Invalid build output directory.");
const previous = await lstat(dist).catch((error) => {
  if (error.code === "ENOENT") return null;
  throw error;
});
if (previous?.isSymbolicLink())
  throw new Error("Build output must not be a symbolic link or junction.");
await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
// The catalog with sources, for the app: what the arena:bots plugin used to inject.
await mkdir(resolve(web, "src/generated"), { recursive: true });
await writeFile(
  resolve(web, "src/generated/bots.ts"),
  `// Generated by scripts/build.mjs, do not edit.\nexport const BOTS = ${JSON.stringify(bots.map(({ file, ...bot }) => bot))} as const;\n`,
);
// The Angular build: the application shell, its hashed bundles and the match
// worker it references. apps/web needs its own `npm ci` first.
await promisify(execFile)(process.execPath, [resolve(web, "node_modules/@angular/cli/bin/ng.js"), "build"], { cwd: web, maxBuffer: 16 * 1024 * 1024 })
  .then(({ stdout }) => process.stdout.write(stdout.split("\n").filter((line) => /Initial total|WARNING|ERROR/.test(line)).join("\n") + "\n"));
await cp(resolve(web, "dist/web/browser"), dist, { recursive: true });
// The bot worker is spawned by the match worker, which the Angular build does
// not follow: it is bundled here, next to the app.
await build({
  absWorkingDir: root,
  entryPoints: { "bot-worker": "packages/runtime/bot-worker.js" },
  bundle: true, format: "esm", outdir: dist, platform: "browser", target: "es2022", minify: true, logLevel: "warning",
});
// Music, standings and the Search Console file; the stylesheet is bundled by the app.
await cp(resolve(root, "packages/viewer/public"), dist, { recursive: true, filter: (src) => !src.endsWith("style.css") });
await writeFile(resolve(dist, "replays.json"), "[]\n");
// Static pages, sitemap, robots and llms.txt for readers that never run the app.
// The Bot Lab page shows the minimal controller from the specification itself,
// so the template on the site is always the template agents are given.
const specification = await readFile(resolve(root, "AGENTS.md"), "utf8");
const site = renderSite({
  index: await readFile(resolve(dist, "index.html"), "utf8"),
  bots,
  standings: await readFile(resolve(dist, "standings.json"), "utf8").then(JSON.parse, () => null),
  example: specification.match(/### Minimal example\s+```\w*\n([\s\S]*?)```/)?.[1] ?? "",
  ...(process.env.SITE_URL ? { baseUrl: process.env.SITE_URL } : {}),
});
for (const [path, content] of site) {
  const file = resolve(dist, path);
  if (!file.startsWith(dist + sep)) throw new Error("Generated page outside the build output.");
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, content);
}
console.log(`Build ready in dist/, ${site.size} static files. Start with: npm run viewer`);
